### ISSUE TITLE
Api-fy the enchantments

### ISSUE THREAD

**Issue by wergat** [wergat/DungeonMap#31]
Including putting the /enchant command into cmd or so

**Comment by atenfyr** [comment]
Why?

**Comment by wergat** [comment]
So we have some more API support for mods using thier own enchantments, and we have better controll over the way enchantments are put on items

**Comment by atenfyr** [comment]
advitem handles it all, and you just edit the /give otherwise

**Comment by wergat** [comment]
Done!
